services:
  backend:
    develop:
      watch:
        - action: sync
          path: ./tms.backend/src
          target: /app/src
        - action: rebuild
          path: ./tms.backend/package.json

  frontend:
    develop:
      watch:
        - action: sync
          path: ./tms.frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./tms.frontend/package.json
